expandContractions=function (text) {
  ExpPosts = text
  ExpPosts = gsub("\\bI['’]m\\b"     , "I AM"      , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bYou['’]re\\b"  , "YOU ARE"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWe['’]re\\b"   , "WE ARE"    , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bThey['’]re\\b" , "THEY ARE"  , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bHe['’]s\\b"    , "HE IS"     , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bShe['’]s\\b"   , "SHE IS"    , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bIt['’]s\\b"    , "IT IS"     , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bThat['’]s\\b"  , "THAT IS"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bThere['’]s\\b" , "THERE IS"  , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWho['’]s\\b"   , "WHO IS"    , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWhat['’]s\\b"  , "WHAT IS"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWhere['’]s\\b" , "WHERE IS"  , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWhen['’]s\\b"  , "WHEN IS"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bHow['’]s\\b"   , "HOW IS"    , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWhy['’]s\\b"   , "WHY IS"    , ExpPosts, ignore.case=T)

  ExpPosts = gsub("\\bIsn['’]t\\b"   , "IS NOT"    , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bAren['’]t\\b"  , "ARE NOT"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWasn['’]t\\b"  , "WAS NOT"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bDoesn['’]t\\b" , "DOES NOT"  , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bHaven['’]t\\b" , "HAVE NOT"  , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bCan['’]t\\b"   , "CAN NOT"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bDon['’]t\\b"   , "DO NOT"    , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWon['’]t\\b"   , "WILL NOT"  , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bCouldn['’]t\\b", "COULD NOT" , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWouldn['’]t\\b", "WOULD NOT" , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bDidn['’]t\\b"  , "DID NOT"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bHadn['’]t\\b"  , "HAD NOT"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWeren['’]t\\b" , "WERE NOT" , ExpPosts, ignore.case=T)

  ExpPosts = gsub("\\bI['’]ve\\b"    , "I HAVE"    , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bYou['’]ve\\b"  , "YOU HAVE"  , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWe['’]ve\\b"   , "WE HAVE"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bThey['’]ve\\b" , "THEY HAVE" , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWho['’]ve\\b"  , "WHO HAVE"  , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWhat['’]ve\\b" , "WHAT HAVE" , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWhere['’]ve\\b", "WHERE HAVE", ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWhen['’]ve\\b" , "WHEN HAVE" , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bHow['’]ve\\b"  , "HOW HAVE"  , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWhy['’]ve\\b"  , "WHY HAVE"  , ExpPosts, ignore.case=T)

  ExpPosts = gsub("\\bHe['’]d\\b"    , "HE HAD"    , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bShe['’]d\\b"   , "SHE HAD"   , ExpPosts, ignore.case=T)

  ExpPosts = gsub("\\bI['’]d\\b"     , "I WOULD"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bYou['’]d\\b"   , "YOU WOULD" , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWe['’]d\\b"    , "WE WOULD"  , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWho['’]d\\b"   , "WHO WOULD" , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bThey['’]d\\b"  , "THEY WOULD", ExpPosts, ignore.case=T)

  ExpPosts = gsub("\\bI['’]ll\\b"    ,"I WILL"     , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bHe['’]ll\\b"   ,"HE WILL"    , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bShe['’]ll\\b"  ,"SHE WILL"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bIt['’]ll\\b"   ,"IT WILL"    , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWe['’]ll\\b"   ,"WE WILL"    , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bThey['’]ll\\b" ,"THEY WILL"  , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWho['’]ll\\b"  ,"WHO WILL"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWhat['’]ll\\b" ,"WHAT WILL"  , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWhere['’]ll\\b","WHERE WILL" , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWhen['’]ll\\b" ,"WHEN WILL"  , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bHow['’]ll\\b"  ,"HOW WILL"   , ExpPosts, ignore.case=T)
  ExpPosts = gsub("\\bWhy['’]ll\\b"  ,"WHY WILL"   , ExpPosts, ignore.case=T)

  ExpPosts = gsub("\\bLet['’]s\\b"   ,"LET US"     , ExpPosts, ignore.case=T)
}
